/*=================================================================*/
/*===HOME===*/
//English
$(function () {
    $(".en").click(function () {

        $(".title_main").text("The economy of video games");
        $(".subtitleTr").text("In this site you will find the history and economy of the main video game production houses with the aim of showing the exponential growth of the video game market over the years");
        $(".psTr").text("History and economy of Playstation");
        $(".ninTr").text("History and economy of Nintendo");
        $(".xbTr").text("History and economy of Xbox");
        $(".sgTr").text("History and economy of Sega");
        $(".creditsTr_1").text("Website created by: Gioele Falaschi, Leonardo Canu, Enrico Marinelli e Samuele Maranghi");
        $(".creditsTr_2").text("Sources: Playstation-Wikipedia, Nintendo-Wikipedia, Xbox-Wikipedia, Sega-Wikipedia, History of Video Game Consoles- Wikipedia");

    });
});

//Italian
$(function () {
    $(".it").click(function () {

        $(".title_main").text("L'economia dei Videogiochi");
        $(".subtitleTr").text("In questo sito troverete la storia e l'economia delle principali case di produzioni di videogiochi con l'obiettivo di mostrare l'esponenziale crescita del mercato videoludico negli anni");
        $(".psTr").text("Storia ed economia di Playstation");
        $(".ninTr").text("Storia ed economia di Nintendo");
        $(".xbTr").text("Storia ed economia di Xbox");
        $(".sgTr").text("Storia ed economia di Sega");
        $(".creditsTr_1").text("Sito web realizzato da: Gioele Falaschi, Leonardo Canu, Enrico Marinelli e Samuele Maranghi");
        $(".creditsTr_2").text("Fonti: Playstation-Wikipedia, Nintendo-Wikipedia, Xbox-Wikipedia, Sega-Wikipedia, History of Video Game Consoles- Wikipedia");

    });
});



/*=================================================================*/
/*===PLAYSTATION===*/

//English
$(function () {
    $(".en").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescPS").text("In the late 1980s, the gaming West was dominated by two champions: SEGA and Nintendo.In order to counter the advance of its rival, Nintendo approached Sony, which at the time already represented an entertainment giant, albeit not a playful one. the initial agreement involved the creation of a CD drive for Super Nintendo, and a combined unit called the PlayStation or Super NES CD-ROM System, which would have to amalgamate both the CD player and the cartridges in a single solution. And that was how engineer Ken Kutaragi, otherwise known as the father of PlayStation, entered the game. The merits for the birth of the console are due to him: however, initially, the idea for a video game console was strictly rejected. Nintendo chose to secretly break the agreement: the contract in fact provided for control over the distribution of CD-Roms by Sony, and would therefore have caused the company a considerable loss in economic terms.Clearly this strategic move was not well received by Ohga, who recanted his initial beliefs and gave the green light to Kutaragi to start production of the console. Sony then reacted to Nintendo's 'betrayal' and forcefully entered the gaming world.");
        $(".Tr_desc_ps1").text("The first PlayStation was released in Japan on December 3, 1994. It was part of the fifth generation of video game consoles, in the heyday of consoles and the new era. The original PlayStation hit the market in time to compete with the Sega Saturn and Nintendo 64. It would also quickly become the best-selling console of the time, becoming the first video game console to sell 120 million units. If nothing else, Sony's PlayStation would change the world of video games forever.");
        $(".Tr_desc_ps2").text("On March 4, 2000, the PlayStation 2 was launched in Japan. As part of the sixth generation of consoles, it rivaled Microsoft's Xbox, Nintendo's GameCube and Sega's Dreamcast.Arguably one of the most successful systems ever, the PlayStation 2 has sold over 150 million units worldwide over a 12-year production run. Some publishers even released PS2-specific games as late as 2013, underscoring how popular the console truly was.The PlayStation2 was the first console to use DVD technology. This has allowed developers to use much more data to make games.The PS2's ability to play most PlayStation games made it the first console to also support backwards compatibility.Also, the PS2 Slim was released in 2004, which offered a slimmer and smaller case and was much quieter than previous models.");
        $(".Tr_desc_psp").text("PlayStation portable is Sony's portable console. Its development was announced at E³ 2003 and was officially unveiled on May 11, 2004 at a pre-E3 press conference. The console was marketed worldwide between December 2004 and September 2005. It offers the possibility of playing video games, watching videos, listening to music, viewing images and using a browser. All these features made the PSP the leading mobile entertainment device of the time.Since September 2007 Sony has introduced a new version of the console called PSP Slim & Lite also called PSP 2000; 2004. This one is 33% lighter and 19% thinner.Since October 1, 2009, the new PSP Go has been on the market, which has a 3.8-inch screen, 16 GB flash memory and Bluetooth.The PSP concluded its commercial season with more than 80 million copies sold.");
        $(".Tr_desc_ps3").text("After initial delays due to production issues, Sony ushered in the era of high-definition gaming with the launch of its third PlayStation on November 11, 2006.The PS3 adopted the Blu-ray disc format, further increasing the storage space to 500GB as production progressed. Additionally, the console included WiFi connectivity and a number of USB options.The services PlayStation Network, PlayStation Store and the PlayStation Plus subscription service were also launched. These services allowed gamers to purchase and download games, play online multiplayer games with friends, and receive exclusive access to upcoming titles with special discounts.The PS3 didn't sell as well as previous versions. It struggled to compete with the gameplay that defined the Nintendo Wii era. Also, the fact that Microsoft's Xbox 360 launched earlier proved problematic.In an effort to cut costs Sony released the PS3 slim on August 18, 2009. In addition to the slimmer design, the unit required less power to operate.Six years after the console's initial release, a PS3 Super Slim was launched on September 25, 2012. The Super Slim was smaller and lighter than the Slim, incorporating a sliding top disc insertion mechanism.Despite all this, the PlayStation 3 reached 88 million copies sold.");
        $(".Tr_desc_ps4").text("Released on November 15, 2013, the PlayStation 4 represented Sony's foray into the eighth generation of video game consoles. It incorporates a number of features relevant to the era such as HDR compatibility, 4K and the all new VR. This way the game design is greatly simplified for the developers.The PS4 places emphasis on sharing and social interaction. Highlighted by the inclusion of a 'Share' button on the controller and Remote Play. The proprietary software is particularly revolutionary as it allows gamers to take clips or screenshots while playing.Unlike PS3, PS4 launched with great fanfare and sold very well. Many praised the system for the quality of the hardware and performance, particularly when compared to the competing Xbox One. Sony has sold over 117 million copies worldwide. Driven by the numerous exclusives.Staying true to form, Sony released the PlayStation 4 Slim in September 2016. As has become the norm, the revised model is significantly smaller than the original. Announced in parallel with the Slim version, Sony released the PlayStation Pro on November 10, 2016. Much more than a revision, the Pro is essentially an updated PS4 but showing better performance than the original within which all PS4 games are compatible .");
        $(".Tr_desc_ps5").text("The first news of a successor to the PlayStation 4 leaked in an interview in April 2019. Sony predicted that the PlayStation 5 would be its next-generation console and would ship worldwide by the end of 2020. Subsequently Sony unveiled the PS5 hardware specs and logo at CES 2020 on January 7, 2020.A big revolution is the new controller, already presented on April 7, 2020: the DualSense. Compared to the previous controllers, the design characterized by a double tone of colors is also revised. Sony claims that the DualSense is less bulky and lighter than the previous one.Thanks to the adaptive triggers that can change the resistance the controller will also offer strong tactile feedback and is intended to offer a better gaming experience.During November 2020 this new console was launched, much more powerful than those released so far. It had a spectacular debut, capable of beating that of the PS4: PlayStation 5 managed to break the US record for the best launch in console history, previously held by PS4. The record concerns both the number of consoles sold compared to the previous generation of PlayStation consoles and the overall turnover.");

        /*Prezzo-Unità*/
        $(".tr_price_ps1").text("Introductory Price: $299.99");
        $(".tr_units_ps1").text("Total units sold: 102 million");
        $(".tr_price_ps2").text("Introductory Price: $299.99");
        $(".tr_units_ps2").text("Total units sold: 155 million");
        $(".tr_price_psp").text("Introductory Price: $170.00");
        $(".tr_units_psp").text("Total units sold: 31 million");
        $(".tr_price_ps3").text("Introductory Price: $299.99");
        $(".tr_units_ps3").text("Total units sold: 80 million");
        $(".tr_price_ps4").text("Introductory Price: $399.99");
        $(".tr_units_ps4").text("Total units sold: 117,2 million");
        $(".tr_price_ps5").text("Introductory Price: $599.99");
        $(".tr_units_ps5").text("Total units sold: Not yet possible make an estimate.");
    });
});

//Italian
$(function () {
    $(".it").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescPS").text("Verso la fine degli anni 80, l'Occidente videoludico era dominato da due campioni: SEGA e Nintendo. Allo scopo di controbattere l'avanzata della rivale, Nintendo si avvicinò a Sony, che già rappresentava all'epoca un colosso dell'intrattenimento, seppur non di stampo ludico. l'accordo iniziale prevedeva la realizzazione di un CD drive per Super Nintendo, e di un'unità combinata chiamata PlayStation o Super NES CD-ROM System, che avrebbe dovuto amalgamare in un'unica soluzione sia il lettore CD che le cartucce. E fu così che entrò in campo l'ingegnere Ken Kutaragi, altrimenti noto come il papà di PlayStation. Spettano a lui i meriti per la nascita della console: tuttavia inizialmente, l'idea per una console di videogiochi venne rigorosamente bocciata. Nintendo scelse di rompere segretamente l'accordo: il contratto prevedeva infatti il controllo sulla distribuzione dei CD-Rom da parte di Sony, e avrebbe pertanto causato all'azienda una considerevole perdita in termini economici. Chiaramente questa mossa strategica non fu ben accolta da Ohga, il quale ritrattò le sue convinzioni iniziali e diede il via libera a Kutaragi per avviare la produzione della console. Sony reagì quindi al 'tradimento' di Nintendo ed entrò di prepotenza nel mondo del gaming.");
        $(".Tr_desc_ps1").text("La prima PlayStation fu rilasciata in Giappone il 3 dicembre 1994. Faceva parte della quinta generazione di console per videogiochi, nel periodo di massimo splendore delle console e della nuova era. La PlayStation originale raggiunse il mercato in tempo per competere con il Sega Saturn e il Nintendo 64. In breve tempo sarebbe diventata anche la console più venduta dell'epoca, diventando la prima console per videogiochi a vendere 120 milioni di unità. Se non altro, la PlayStation di Sony avrebbe cambiato per sempre il mondo dei videogiochi.");
        $(".Tr_desc_ps2").text("Il 4 marzo 2000 la PlayStation 2 è stata lanciata in Giappone. Come parte della sesta generazione di console, rivaleggiava con Xbox di Microsoft, GameCube di Nintendo e il Dreamcast di Sega. Probabilmente uno dei sistemi di maggior successo di sempre, la PlayStation 2 ha venduto oltre 150 milioni di unità in tutto il mondo con un ciclo di produzione durato oltre 12 anni. Alcuni editori hanno persino rilasciato giochi specifici per PS2 fino al 2013, sottolineando quanto fosse veramente popolare la console. La PlayStation2 è stata la prima console a utilizzare la tecnologia DVD. Ciò ha consentito agli sviluppatori di utilizzare molti più dati per creare giochi. La capacità della PS2 di riprodurre la maggior parte dei giochi PlayStation l'ha resa la prima console a supportare anche la retrocompatibilità. Inoltre, nel 2004 è stata lanciata la PS2 Slim, che offriva un case più sottile e più piccolo ed era molto più silenziosa rispetto ai modelli precedenti.");
        $(".Tr_desc_psp").text("PlayStation portable è la console portabile di Sony. Il suo sviluppo è stato annunciato all'E³ del 2003 ed è stata svelata ufficialmente l'11 maggio 2004 a una conferenza stampa prima dell'E3. La console è stata commercializzata in tutto il mondo tra il dicembre 2004 e il settembre 2005. Offre la possibilità di giocare con i videogiochi, vedere video, ascoltare musica, visualizzare immagini e utilizzare un browser. Tutte queste caratteristiche hanno fatto della PSP il principale dispositivo di intrattenimento mobile dell'epoca. Dal settembre 2007 Sony ha introdotto una nuova versione della console chiamata PSP Slim & Lite denominata anche PSP 2000; 2004. Questa è del 33% più leggera e del 19% più sottile. Dal 1 ottobre 2009 è in commercio la nuova PSP Go, che possiede uno schermo di 3,8 pollici una memoria flash da 16 GB e il Bluetooth. La PSP ha concluso la sua stagione commerciale con più di 80 milioni di copie vendute.");
        $(".Tr_desc_ps3").text("Dopo i ritardi iniziali dovuti a problemi di produzione, Sony ha fatto il suo ingresso nell'era dei giochi ad alta definizione con il lancio della sua terza playstation, l'11 novembre 2006. La PS3 ha adottato il formato del disco Blu-ray, aumentando ulteriormente lo spazio di archiviazione che con il progredire della produzione sè arrivato fino a 500 GB. Inoltre, la console includeva la connettività WiFi e una serie di opzioni USB. Sono stati lanciati anche i servizi PlayStation Network, PlayStation Store e il servizio di abbonamento PlayStation Plus. Questi servizi hanno consentito ai giocatori di acquistare e scaricare giochi, prendere parte a giochi multiplayer on-line con gli amici, e ricevere l'accesso esclusivo ai titoli in arrivo con sconti speciali. La PS3 non si è venduta così bene come le versioni precedenti. Ha faticato a competere con il gameplay che ha definito l'era del Nintendo Wii. Inoltre, il fatto che la Xbox 360 di Microsoft sia stata lanciata prima si è rivelato problematico. Nel tentativo di tagliare i costi Sony ha rilasciato la PS3 slim il 18 agosto 2009. Oltre al design più sottile, l'unità richiedeva meno energia per funzionare. Sei anni dopo il rilascio iniziale della console, il 25 settembre 2012 è stata lanciata una PS3 Super Slim. La Super Slim era più piccola e leggera della Slim, incorporando un meccanismo di inserimento del disco superiore scorrevole. Nonostante tutto ciò, la PlayStation 3 raggiunse gli 88 milioni di copie vendute.");
        $(".Tr_desc_ps4").text("Rilasciata il 15 novembre 2013, la PlayStation 4 ha rappresentato l'incursione di Sony nell'ottava generazione di console per videogiochi. Incorpora una serie di caratteristiche rilevanti per l'epoca come compatibilità HDR, 4K e il nuovissimo VR. In questo modo il design del gioco è notevolmente semplificato per gli sviluppatori. La PS4 pone l'accento sulla condivisione e l'interazione sociale. Evidenziato dall'inclusione di un pulsante 'Condividi' sul controller e dalla riproduzione remota. Il software proprietario è particolarmente rivoluzionario in quanto consente ai giocatori di effettuare clip o screenshot durante il gioco. A differenza di PS3, PS4 è stata lanciata in pompa magna e ha venduto molto bene. Molti hanno elogiato il sistema per la qualità dell'hardware e le prestazioni, in particolare rispetto alla Xbox One concorrente. Sony ha venduto oltre 117 milioni di copie in tutto il mondo. Spinta dalle numerose esclusive. Rimanendo fedele alla forma, Sony ha rilasciato PlayStation 4 Slim a settembre 2016. Come è diventata la norma, il modello rivisto è significativamente più piccolo dell'originale. Annunciata parallelamente alla versione Slim, Sony ha rilasciato la PlayStation Pro il 10 novembre 2016. Molto più di una revisione, la Pro è essenzialmente una PS4 aggiornata ma che mostra prestazioni migliori rispetto all'originale all'interno della quale tutti i giochi PS4 sono compatibili.");
        $(".Tr_desc_ps5").text("Le prime notizie su un'erede della PlayStation 4 trapelarono in un'intervista nell'aprile 2019. Sony prevedeva che la PlayStation 5 sarebbe stata la sua console next-generation e che sarebbe stata spedita in tutto il mondo entro la fine del 2020. Successivamente, il 7 gennaio 2020, in occasione del CES 2020, Sony ha svelato le specifiche hardware e il logo di PS5. Una grossa rivoluzione è il nuovo controller, presentato già il 7 aprile 2020: il DualSense. Rispetto ai precedenti controller viene rivisto anche il design caratterizzato da una doppia tonalità di colori. Sony afferma che rispetto al precedente il DualSense è meno ingombrante e più leggero. Grazie ai grilletti adattivi che possono modificare la resistenza il controller offrirà anche un forte feedback tattile ed ha lo scopo di offrire una migliore esperienza di gioco. Durante il novembre 2020 fu lanciata questa nuova console, molto più potente di quelle uscite fino ad ora. Ebbe un debutto spettacolare, in grado di battere quello avuto dalla PS4: PlayStation 5 è riuscita a battere il record USA per il miglior lancio nella storia delle console, precedentemente detenuto da PS4. Il record riguarda sia il numero di console vendute rispetto alla precedente generazione di console PlayStation che il fatturato complessivo.");

        /*Prezzo-Unità*/
        $(".tr_price_ps1").text("Prezzo di lancio: $299,99");
        $(".tr_units_ps1").text("Totale unità vendute: 102 milioni");
        $(".tr_price_ps2").text("Prezzo di lancio: $299,99");
        $(".tr_units_ps2").text("Prezzo di lancio: $299,99");
        $(".tr_price_psp").text("Prezzo di lancio: $170,00");
        $(".tr_units_psp").text("Totale unità vendute: 31 milioni");
        $(".tr_price_ps3").text("Prezzo di lancio: $299,99");
        $(".tr_units_ps3").text("Totale unità vendute: 80 milioni");
        $(".tr_price_ps4").text("Prezzo di lancio: $399,99");
        $(".tr_units_ps4").text("Totale unità vendute: 117,2 milioni");
        $(".tr_price_ps5").text("Prezzo di lancio: $599,99");
        $(".tr_units_ps5").text("Totale unità vendute: Non è ancora possible effetuare una stima.");
    });
});

/*=================================================================*/
/*===XBOX===*/

//English
$(function () {
    $(".en").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescXbox").text("It was born in 1998 from the idea of ​​a now ex employee, who decided to disassemble some 'Dell' laptops to assemble a first prototype of the console. Together with him embarked on this project, codenamed 'DirectX Box', also Kevin Bachus, Otto Berkes and Ted Hase. The first response from Bill Gates was anything but positive. The production of a game console manufactured by Microsoft, without Windows as an operating system, was deemed a waste of money and also an insult to Gates' work. The upper floors, however, had to change their mind. Faced with the undeniable reality that Sony, sooner or later, given its success with PlayStation, could become a problem for Microsoft, so the two thought again. Thus they gave the green light to the production of the first Xbox. Microsoft's idea was to enter the market and enter into direct competition with Playstation and Sony, thanks to a console, later renamed Xbox with an architecture similar to that of PCs but with twice the power of what would later be had to be the PlayStation 2. So Microsoft entered the world of video games “only” in 2001.");
        $(".Tr_desc_xbox").text("This console represented the first attempt to enter the gaming market by the aforementioned Microsoft. Already announced a year earlier, Xbox was technically more powerful than its competitors, with internal components that could be found in a common computer of the time. It was also noted for its PC-like size and weight, and was the first console to have a built-in hard drive.The launch of the console was organized in a big way and took place as planned on November 15, 2001 in Times Square, in New York and in Italy and in all countries of the Eurozone the cost was a good 479 €. Xbox went on to sell a total of 24 million units.");
        $(".Tr_desc_xbox360").text("After the first generation of Microsoft consoles, the electronics giant was more determined than ever to continue the path of Xbox. The intent was to once again produce the most powerful console on the market. On May 12, 2005, Microsoft introduced the Xbox 360 to the world, announcing its release in November. Although the Xbox 360 was on paper more powerful than the rival PlayStation 3, the time factor was a problem for Microsoft, as they rushed production to get the console out before Sony. While on the one hand coming out a year earlier than the competition bore fruit, on the other the beginnings were far from positive. Then there was the launch of the Kinect, a peripheral created following the launch of the Wii by Nintendo and the explosion of motion gaming. Peripheral unfortunately never properly supported. Xbox 360 has shaped the concept of modern gaming, thanks to the introduction of achievements, the ability to install titles to the hard drive from the dashboard and the advanced online infrastructure. Speaking of figures, the seventh generation closed with 75 million consoles sold worldwide, a commercial success for Microsoft.");
        $(".Tr_desc_xboxOne").text("We are in 2011 and the rumors about the arrival of a new generation of consoles are already starting to circulate. After releasing several details, Xbox One is officially shown in November 2013.The eighth generation starts on the wrong foot for Microsoft. The vision of the Xbox team does not meet the favor of gamers and the 'always online' policy is not welcome. The presentation of the console goes down in history as perhaps the lowest point ever touched by the brand. Another point against are the 100 euros more than Playstation 4, due to a Kinect 2 included in the package, leading the mass not to choose the Microsoft console as a point of reference.Xbox One changes face but the domain remains of Sony and PlayStation 4.Years go by and the S version takes the place of the base, Microsoft decides to develop a new mid-gen console: the most powerful console of the eighth generation.The Xbox world is slowly changing its face, players feel this. The console enters the market and homes in a disruptive way but there is still a problem that Microsoft has to solve: the lack of exclusives.Microsoft Game Studios changes its name to Xbox Game Studios and acquires some external studios: the transformation is complete.The eighth generation thus comes to an end, once again between lights and shadows. The results are certainly not those estimated in 2011 but the road taken is the right one. Years have passed since the presentation in 2013 and a curious thing has happened: the market and gamers have moved to the digital format. The world of video games is now strongly linked to that now distant concept of always online. The initial vision of Xbox One turns out to be correct, but the time was not right. The market had to evolve naturally.According to a report from August 2021, Xbox One has sold a whopping 57 million copies.");
        $(".Tr_desc_xboxSeriesX").text("The end of 2020 also brought with it the long-awaited generational leap and the new Xbox Series X and S are representing a real rebirth for the brand, after the gloomy generation of One. The first year of the consoles has certainly made it clear that there is a lot of interest from the market for Microsoft's gaming proposal, and this is coming thanks to a clear change of course on the communication front. Microsoft has reinvented gaming not with the new consoles but with its Game Pass service, the Netflix of video games: with 14 euros a month for its Ultimate version, a library of over 100 games is included.");

        /*Prezzo-Unità*/
        $(".tr_price_xbox").text("Introductory Price: $299.99");
        $(".tr_units_xbox").text("Total units sold: 24 million");
        $(".tr_price_xbox360").text("Introductory Price: $299.99");
        $(".tr_units_xbox360").text("Total units sold: 80 million");
        $(".tr_price_xboxOne").text("Introductory Price: $299.99");
        $(".tr_units_xboxOne").text("Total units sold: 58.5 million");
        $(".tr_price_xboxSeriesX").text("Introductory Price: $599.99");
        $(".tr_units_xboxSeriesX").text("Total units sold: Not yet possible make an estimate.");
    });
});

//Italian
$(function () {
    $(".it").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescXbox").text("Nacque nel 1998 dall’idea di un ormai ex dipendente, che decise di smontare alcuni portatili della 'Dell' per assemblare un primo prototipo della console. Insieme a lui si imbarcarono su questo progetto, nome in codice “DirectX Box”, anche Kevin Bachus, Otto Berkes e Ted Hase. Il primo responso da parte di Bill Gates fu tutt’altro che positivo. La produzione di una console da gioco prodotta da Microsoft, senza Windows come sistema operativo, venne ritenuta come uno spreco di soldi e anche come un insulto nei confronti del lavoro di Gates. I piani alti dovettero però ricredersi. Messi davanti a l’innegabile realtà che Sony, presto o tardi, dato il successo con PlayStation, sarebbe potuta diventare un problema per Microsoft, così i due ci ripensarono. Diedero così il via libera alla produzione della prima Xbox. L’idea di Microsoft era quella di introdursi nel mercato e di entrare in diretta competizione con Playstation e Sony, grazie ad una console, poi rinominata Xbox con un’architettura simile a quella dei PC ma con una potenza doppia rispetto a quella che poi sarebbe dovuta essere la PlayStation 2. Così Microsoft entrò a far parte del mondo dei videogiochi “soltanto” nel 2001.");
        $(".Tr_desc_xbox").text("Questa console ha rappresentato il primo tentativo di entrare nel mercato videoludico da parte della suddetta Microsoft. Annunciata già un anno prima, Xbox, era tecnicamente più potente rispetto alle sue concorrenti, con dei componenti interni che potevano trovarsi in un comune computer del tempo. Era nota anche per le sue dimensioni e il suo peso simile a quello di un PC ed è stata la prima console a disporre di un disco rigido incorporato. Il lancio della console fu organizzato in grande e avvenne come pianificato il 15 novembre 2001 a Times Square, in New York e in Italia e in tutti i paesi della zona euro il costo fu di ben 479 €. Xbox arrivò a vendere un totale di 24 milioni di pezzi.");
        $(".Tr_desc_xbox360").text("Terminata la prima generazione di console Microsoft, il gigante dell’elettronica era più che mai deciso a portare avanti il percorso di Xbox. L’intento era quello di produrre ancora una volta la console più potente sul mercato. Il 12 maggio 2005 Microsoft presentava al mondo Xbox 360, annunciandone l’uscita a novembre. Nonostante Xbox 360 fosse sulla carta più potente rispetto alla rivale PlayStation 3, il fattore tempo costituì un problema per Microsoft, dato che ne affrettò la produzione per far uscire prima la console rispetto a Sony. Se da un lato uscire un anno prima rispetto alla concorrenza portò i suoi frutti, dall’altro gli inizi furono tutt’altro che positivi. Vi è stato poi il lancio del Kinect, periferica creata in seguito al lancio della Wii da parte di Nintendo e l’esplosione del motion gaming. Periferica purtroppo mai supportata adeguatamente. Xbox 360 ha plasmato il concetto di gaming moderno, grazie all’introduzione degli obiettivi, la possibilità di installare i titoli sul disco rigido dalla dashboard e l’avanzata infrastruttura online. Parlando di cifre, la settima generazione si è chiusa con 75 milioni di console vendute in tutto il mondo, un successo commerciale per Microsoft.");
        $(".Tr_desc_xboxOne").text("Siamo nel 2011 e i rumor sull’arrivo di una nuova generazione di console iniziano già a circolare. Dopo aver diffuso diversi dettagli, nel novembre del 2013 viene ufficialmente mostrata Xbox One. L’ottava generazione inizia con il piede sbagliato per Microsoft. La visione del team Xbox non incontra il favore dei videogiocatori e la politica 'dell’always online' non è gradita. La presentazione della console passa alla storia come forse il punto più basso mai toccato dal marchio. Un altro punto a sfavore sono i 100 euro in più rispetto a Playstation 4, a causa di un Kinect 2 inserito obbligatoriamente nella confezione, portando la massa a non scegliere la console Microsoft come punto di riferimento. Xbox One cambia faccia ma il dominio resta di Sony e PlayStation 4. Gli anni passano e la versione S prende il posto della base, Microsoft decide di sviluppare un nuova console mid-gen: la console più potente dell’ottava generazione. Il mondo Xbox sta lentamente cambiando faccia, i giocatori questo lo avvertono. La console entra nel mercato e nelle case in modo dirompente ma c’è ancora un problema che Microsoft deve risolvere: la mancanza di esclusive. I Microsoft Game Studios cambiano nome diventando Xbox Game Studios e acquisisce alcuni stidi esterni: la trasformazione è completa. L’ottava generazione volge così al termine, anche questa volta tra luci e ombre. I risultati non sono certo quelli preventivati nel 2011 ma la strada intrapresa è quella giusta. Sono passati anni dalla presentazione nel 2013 e una cosa curiosa è accaduta: il mercato e i videogiocatori si sono spostati sul formato digital. Il mondo dei videogiochi è ora fortemente legato a quell’ormai lontano concetto di always online. La visione iniziale di Xbox One si rivela essere corretta, i tempi però non erano maturi. Il mercato doveva evolversi in modo naturale. Secondo un rapporto dell'Agnosto 2021, Xbox One ha venduto ben 57 milioni di copie.");
        $(".Tr_desc_xboxSeriesX").text("La fine del 2020 ha portato con sé anche il tanto atteso salto generazionale e le nuove Xbox Series X e S stanno rappresentando una vera e propria rinascita per il brand, dopo la generazione cupa di One. Il primo anno delle console ha certamente reso evidente come ci sia tanto interesse da parte del mercato per la proposta gaming di Microsoft, e questo sta venendo grazie ad un netto cambio di rotta sul fronte della comunicazione. Microsoft ha reinventato il gaming non con le nuove consoles ma con il suo servizio Game Pass, il Netflix dei videogiochi: con 14 euro al mese per la sua versione Ultimate è compresa una libreria di oltre 100 giochi.");

        /*Prezzo-Unità*/
        $(".tr_price_xbox").text("Prezzo di lancio: $299,99");
        $(".tr_units_xbox").text("Totale unità vendute: 24 milioni");
        $(".tr_price_xbox360").text("Prezzo di lancio: $299,99");
        $(".tr_units_xbox360").text("Totale unità vendute: 80 milioni");
        $(".tr_price_xboxOne").text("Prezzo di lancio: $299,99");
        $(".tr_units_xboxOne").text("Totale unità vendute: 58,5 milioni");
        $(".tr_price_xboxSeriesX").text("Introductory Price: $599.99");
        $(".tr_units_xboxSeriesX").text("Totale unità vendute: Non è ancora possible effetuare una stima.");
    });
});

/*=================================================================*/
/*===NINTENDO===*/

//English
$(function () {
    $(".en").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescNin").text("Nintendo Co. Ltd. is a Japanese company specializing in the production of video games and consoles. Regarded as one of Japan's largest companies, Nintendo was founded on September 23, 1889 by Yamauchi Fusajirō as a manufacturer and distributor of playing cards. Throughout its history it has made several mechanical and electronic games, then entering the world of video games in the seventies, as a producer of arcade games. Since the eighties Nintendo has produced numerous tabletop and portable consoles that have sold over 750 million units. In 1973 the Nintendo Research & Development Department creates the Laser Clay Shooting System, a clay pigeon shooting simulator that perfects the technology of optical guns already marketed by the company. The system is designed to be installed in large venues, such as Japanese bowling alleys, which are going through a period of crisis due to the novelty represented by karaoke venues. The following year, a more compact version was created, the Mini Laser Clay, designed for game rooms. With Wild Gunman (1974) Nintendo inaugurates the Simulation System series: six arcade cabinets that use light guns combined with 16mm film footage Nintendo's first programmed arcade game is Computer Othello (1978) In 1975 Nintendo obtains the rights to distribution in Japan of the Magnavox Odyssey console, containing a tennis video game very similar to Atari's Pong. He then worked on his own version of the machine together with Mitsubishi Electric and in 1977 marketed it under the name of Color TV Game Also in 1977 Nintendo hired the video game developer Shigeru Miyamoto, future creator of Super Mario.");
        $(".Tr_desc_NES").text("The Nintendo Entertainment System (NES), known in Japan as the Famicom was an 8-bit video game console produced by Nintendo between 1983 and 1995. It is considered by many to be the system that revived the video game industry after the crisis of 1983, above all thanks to the success of titles such as Super Mario Bros, The Legend of Zelda and Metroid, of a higher quality level than at the time; the console also introduced a working model now adopted by everyone, namely that of granting licenses for software development to third parties. Considered one of the most important gaming consoles in history, in 1995, the year in which it was definitively taken off the market, it reached almost 62 million units sold, becoming the best-selling game machine of its time. In 2009, IGN named it the best console game of all time.");
        $(".Tr_desc_gameBoy").text("The Game Boy is a handheld monochrome video game console manufactured and marketed by Nintendo between April 21, 1989 and March 23, 2003. Made by the Nintendo Research & Development group 1, led by Gunpei Yokoi and Satoru Okada, it was developed as a successor to the Game & Watch.It became the reference portable system in its time, despite the release of many more advanced competitors, and is one of the most recognized icons in the history of video games. This was the first of a successful series of consoles called Game Boy, with a commercial life of more than twenty years. After some variations of the original, the first real successor was the Game Boy Color. On explicit directives from Nintendo, Gunpei Yokoi's group designed a simple, resistant and low-cost console. It was intended to offer it for an audience of children, or as a portable and economical alternative to the classic tabletop Nintendo Entertainment System. The appearance of the console and the cartridges in fact recall the NES. The focus was on the quality of the games and ease of use. The Game Boy was released in Japan on April 21, 1989 and was an instant success.");
        $(".Tr_desc_SNES").text("The Super Nintendo Entertainment System (SNES), commonly abbreviated to Super Nintendo, is a 16-bit video game console developed by Nintendo and marketed in 1990 in Japan, 1991 in North America and 1992 in Europe; in Japan it is called with the name of Super Famicom; During its lifetime, the Super Nintendo was a major commercial success and soon became the best-selling and most popular console of the 16-bit era, despite a slow start due to the popularity of the competitor Sega Mega Drive, a machine with the which he competed for most of his life. The console remained popular even during the 32-bit era, thanks to a large group of enthusiasts, collectors and producers of homebrew video games, so much so that its final disposal took place only in 2003, after more than thirteen years from the original sale.");
        $(".Tr_desc_nin64").text("The Nintendo 64 (N64 for short) is a tabletop video game console manufactured by Nintendo from 1996 to 2002 and succeeded the Super Nintendo Entertainment System (SNES). The console uses cartridges, although it belongs to a time when these media had become obsolete for tabletop consoles and the competition used CD-ROM. The name refers to the 64 bits of its microprocessor, although the data bus is actually reduced to 32 bits. It was a system strongly oriented towards three-dimensional graphics, thanks to a remarkable graphics coprocessor. The Nintendo 64 was very successful, with over 32 million units sold, but they are far fewer than the competitor PlayStation and even fewer than the SNES");
        $(".Tr_desc_gba").text("The Game Boy Advance, officially abbreviated GBA, is a 32-bit portable console developed, manufactured and marketed by Nintendo in 2001. It succeeds the Game Boy Color. It competed commercially with the WonderSwan Color, the GP32 and the N-Gage, still occupying the majority of the market. It was the first Nintendo portable console to surpass the technical characteristics of the Atari Lynx, characteristics that make the Game Boy Advance similar to the SNES. While using different cartridges than those of the Game Boy and Game Boy Color, the Game Boy Advance remains compatible with the latter thanks to the presence of a Z80 coprocessor, which guarantees backwards compatibility. The Game Boy Advance with its 16.78 MHz ARM7TDMI processor, despite managing some basics of 3D, is not equipped with real hardware support for rendering 3D polygonal graphics, but with the discrete power of the processor it was perfectly possible to 3D world software made of a limited number of polygons, mapped textures, light sources and shadows.");
        $(".Tr_desc_ninCube").text("The Nintendo GameCube, also known as GameCube (abbreviated as NGC in Japan or GCN in Europe and North America), is a console manufactured by Nintendo. It was a sixth generation console, along with the Dreamcast, PlayStation 2 and Xbox. Marketed between 2001 and 2007, the fourth console produced by the Japanese company was announced as a successor to the Nintendo 64 with the codename 'Dolphin' (although it was initially referred to internally as 'N2000' and 'Project Dolphin'). GameCube was the first Nintendo console to use optical discs as its primary storage medium. Its mini-DVD format discs made it a system not designed to play full-sized DVDs or audio CDs, unlike its contemporary competitors, leading the system to specialize exclusively in video games. The console had support for network play, but in a limited way and with few titles, via a broadband connection network card or a 56 kbit/s modem adapter and can connect to the Game Boy Advance handheld console, via dedicated cable, which allows gamers to access exclusive gaming features by using the laptop as a second screen and controller. Reception garnered by the GameCube was generally positive. The console was praised for its controller, large library of high-quality video games and software, but was criticized for its aesthetic appearance and lack of some features.");
        $(".Tr_desc_ninDS").text("The Nintendo DS is a handheld console designed and manufactured by Nintendo, which was introduced in 2004. The console features a clamshell design, and has two LCD screens inside – one of which is a touch screen. The DS also features a built-in microphone and supports IEEE 802.11 wireless (Wi-Fi) connectivity via the Nintendo Wi-Fi Connection online gaming service. It was the first Nintendo console to be released in North America (November 21, 2004) before Japan (December 2, 2004). A few months later it was also released in stores in Australia (February 24, 2005) and, lastly, in Europe (March 11, 2005). It is currently the second best-selling console in history after the PlayStation 2. On European territory it was marketed in 9 colors: white, black, silver, blue, pink, red, grey, green and blue. After more than six years, the entire series of Nintendo DS consoles was joined and then replaced by the Nintendo 3DS, Nintendo's new portable console, which debuted in Europe on March 25, 2011. The console was on the other hand already discontinued in 2009 and the games remained playable for the Nintendo DSi and Nintendo DSi XL until May 20, 2014 when Nintendo announced they would no longer be available, like the Nintendo Wi-Fi Connection service.");
        $(".Tr_desc_wii").text("Wii is a video game console, produced by the Japanese company Nintendo, launched on the market in 2006. Heir to the Nintendo GameCube, its 101.63 million units sold made it the most popular home console of the seventh generation and the second of Nintendo, surpassed only by Nintendo Switch. Wii was the main competitor to Microsoft's Xbox 360 and Sony's PlayStation 3. The console differs from the others of its time, and from the previous ones, for the possibility of interacting with the video game through the movement of the arms, and for having a pointing system at the screen. These two features are not an absolute novelty in the world of video games, but for the first time they have been integrated into a console without resorting to additional peripherals. The cornerstone of the innovation is the controller, called the Wii Remote, in shape it resembles a remote control and can be gripped with one hand, as well as having a fairly classic set of keys, it is equipped with an accelerometer for detecting movement, and a IR sensor placed on its top, this sensor combined with the Sensor Bar (present in the console package) allows pointing to the screen. In the Wii package there is also the Nunchuk, an expansion of the Wii Remote that connects to it via cable and is gripped with one hand, has an accelerometer inside, so as to detect the movements of the second arm, and adds a stick analog and two back buttons.");
        $(".Tr_desc_wiiu").text("Wii U is a video game console manufactured by Nintendo. It succeeds the Wii while not replacing it in some countries and was the first eighth generation tabletop console to hit the market. Its main competitors are Sony's PlayStation 4 and Microsoft's Xbox One. Nintendo began development of the Wii U in 2008, after recognizing some intrinsic limitations of the Wii, seen by the public as a too 'casual' console compared to its main competitors both from a playful and technical point of view. The most common criticisms addressed to the system concerned, for example, the absence of support for high definition and a consistent multiplayer mode on the network. Through Wii U, Nintendo therefore intended to bring 'hardcore' gamers back to its platform and to do this it decided that new hardware was needed. Various ideas were discussed regarding the way forward to achieve the goal and for this reason the project restarted from scratch on several occasions. Finally, after also thinking of installing a small screen on the controller to indicate some information to the player (similar idea to the VMU of the Sega Dreamcast), a gamepad model with a generously sized screen was developed which was initially thought not to be economically feasible.");
        $(".Tr_desc_nin3DS").text("Nintendo 3DS is a handheld video game console manufactured by Nintendo and the first to belong to the eighth generation of video game consoles. Its peculiarity is the upper screen that allows you to view games, images and videos in 3D, without the use of special glasses. It was officially unveiled at E3 2010 on June 15th. On April 14, 2010, during an interview, Nintendo of America president Reggie Fils-Aime confirmed that the 3DS would be Nintendo's new portable console, ushering in the eighth generation of video game consoles once and for all. During the Nintendo Direct on June 22, 2012, Nintendo introduced the Nintendo 3DS XL, a larger version of the current console. On September 17, 2020, almost ten years after the launch of the first model of the console, Nintendo announced its discontinuation and the interruption of production of all models introduced on the market.");
        $(".Tr_desc_ninSwitch").text("Nintendo Switch, initially known by the codename of NX, is a 64-bit console of a hybrid nature developed by Nintendo and released worldwide as of March 3, 2017. Nintendo Switch was officially revealed on October 20, 2016 and is launched in Japan, Europe and North America on March 3, 2017. The Switch represents Nintendo's first attempt to create a hybrid console between a home and a handheld by featuring an electronic cartridge-based media, a previously abandoned format by Nintendo after the Nintendo 64 in the stationary sector but adopted in all portable consoles, which the cartridges for Switch look like. It is Nintendo's second most successful console, surpassed only by the Nintendo DS in terms of units sold, and third overall, behind the PlayStation 2 and the DS itself. It competes commercially with eighth-generation consoles, Sony's PlayStation 4 and Microsoft's Xbox One, a generation in which it is commonly included by the gaming press. However, Nintendo has announced that due to its enormous success, it intends to continue supporting the console for many more years, thus also crossing the entire ninth generation. This led it, in the second part of its production cycle, to divide the market also with PlayStation 5 and Xbox Series X and Series S, marketed at the end of 2020.");

        /*Prezzo-Unità*/
        $(".tr_price_NES").text("Introductory Price: $89,99");
        $(".tr_units_NES").text("Total units sold: 61,91 million");
        $(".tr_price_gameBoy").text("Introductory Price: $89,99");
        $(".tr_units_gameBoy").text("Total units sold: 118 million");
        $(".tr_price_SNES").text("Introductory Price: $199,99");
        $(".tr_units_SNES").text("Total units sold: 49,1 million");
        $(".tr_price_nin64").text("Introductory Price: $199,99");
        $(".tr_units_nin64").text("Total units sold: 32,92 million");
        $(".tr_price_gba").text("Introductory Price $99,99:");
        $(".tr_units_gba").text("Total units sold: 81,5 million");
        $(".tr_price_ninCube").text("Introductory Price: $199,99");
        $(".tr_units_ninCube").text("Total units sold: 21,74 million");
        $(".tr_price_ninDS").text("Introductory Price: $120,00");
        $(".tr_units_ninDS").text("Total units sold: 153,99 million");
        $(".tr_price_wii").text("Introductory Price: $249,99");
        $(".tr_units_wii").text("Total units sold: 101,63 million");
        $(".tr_price_wiiu").text("Introductory Price: $299,99");
        $(".tr_units_wiiu").text("Total units sold: 13,56 million");
        $(".tr_price_nin3DS").text("Introductory Price: $249,99");
        $(".tr_units_nin3DS").text("Total units sold: 76 million");
        $(".tr_price_ninSwitch").text("Introductory Price: $299,99");
        $(".tr_units_ninSwitch").text("Total units sold: 122,55 million");
    });
});

//Italian
$(function () {
    $(".it").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescNin").text("Nintendo Co. Ltd. è un'azienda giapponese specializzata nella produzione di videogiochi e console. Considerata come una delle più grandi compagnie del Giappone, la Nintendo fu fondata il 23 settembre 1889 da Yamauchi Fusajirō come produttore e distributore di carte da gioco. Nel corso della sua storia ha realizzato diversi giochi meccanici ed elettronici, entrando poi nel mondo dei videogiochi negli anni settanta, come produttore di giochi arcade. Dagli anni ottanta Nintendo ha prodotto numerose console da tavolo e portatili che hanno venduto oltre 750 milioni di unità. Nel 1973 il Nintendo Research & Development Department realizza il Laser Clay Shooting System, un simulatore di tiro al piattello che perfeziona la tecnologia delle pistole ottiche già commercializzate dall'azienda. Il sistema è pensato per essere installato in ampi locali, come le sale da bowling giapponesi, che stanno attraversando un periodo di crisi per colpa della novità rappresentata dai locali karaoke.L'anno seguente viene realizzata una versione più compatta, il Mini Laser Clay, pensata per le sale giochi. Con Wild Gunman (1974) Nintendo inaugura la serie Simulation System: sei cabinati da sala giochi che utilizzano pistole ottiche abbinate a filmati in pellicola da 16 millimetri Il primo videogioco arcade programmato di Nintendo è Computer Othello (1978) Nel 1975 Nintendo ottiene i diritti di distribuzione in Giappone della console Magnavox Odyssey, contenente un videogioco di tennis molto simile al Pong di Atari. Lavora quindi a una propria versione della macchina insieme alla Mitsubishi Electric e nel 1977 la commercializza con il nome di Color TV Game Sempre nel 1977 Nintendo assume lo sviluppatore di videogiochi Shigeru Miyamoto, futuro creatore di Super Mario.");
        $(".Tr_desc_NES").text("Il Nintendo Entertainment System (NES), noto in Giappone con il nome di Famicom è stata una console per videogiochi a 8-bit prodotta da Nintendo tra il 1983 e il 1995. È da molti considerato il sistema che ha risollevato l'industria dei videogiochi dopo la crisi del 1983, soprattutto grazie al successo di titoli come Super Mario Bros, The Legend of Zelda e Metroid, di livello qualitativo superiore a quello dell'epoca; la console ha inoltre introdotto un modello lavorativo oggi adottato da tutti, ovvero quello di concedere a terze parti le licenze per lo sviluppo dei software. Considerata una delle più importanti console videoludiche della storia, nel 1995, anno in cui fu tolta definitivamente dal commercio, raggiunse quasi le 62 milioni di unità vendute,diventando la macchina da gioco più venduta della sua epoca. Nel 2009 il sito IGN l'ha definita la migliore console videoludica di tutti i tempi.");
        $(".Tr_desc_gameBoy").text("Il Game Boy è una console portatile per videogiochi monocromatica prodotta e commercializzata da Nintendo tra il 21 aprile 1989 e il 23 marzo 2003. Realizzato dal gruppo Nintendo Research & Development 1, guidato da Gunpei Yokoi e Satoru Okada, venne sviluppato come successore dei Game & Watch.A suo tempo divenne il sistema portatile di riferimento, nonostante l'uscita di molti concorrenti più avanzati, ed è una delle icone più riconosciute della storia dei videogiochi. Questa fu la prima di una fortunata serie di console chiamate Game Boy, con una vita commerciale di più di vent'anni. Dopo alcune varianti dell'originale, il primo successore vero e proprio fu il Game Boy Color. Su esplicite direttive della Nintendo, il gruppo di Gunpei Yokoi progettò una console semplice, resistente e a basso costo. Si intendeva proporla per un pubblico di ragazzini, o come alternativa portatile ed economica al classico da tavolo Nintendo Entertainment System. L'aspetto della console e delle cartucce richiamano infatti il NES. Si puntò sulla qualità dei giochi e sulla semplicità di utilizzo. Il Game Boy fu commercializzato in Giappone il 21 aprile 1989 e fu subito un grande successo.");
        $(".Tr_desc_SNES").text("Il Super Nintendo Entertainment System (SNES),comunemente abbreviato in Super Nintendo, è una console per videogiochi a 16 bit sviluppata da Nintendo e commercializzata nel 1990 in Giappone, nel 1991 in Nord America e nel 1992 in Europa; in Giappone è chiamata col nome di Super Famicom; Durante il suo ciclo di vita, il Super Nintendo ebbe un importante successo commerciale e divenne ben presto la console più venduta e diffusa dell'epoca dei 16-bit,nonostante un inizio a rilento dovuto alla popolarità del concorrente Sega Mega Drive, macchina con la quale competé per buona parte della sua vita. La console rimase popolare anche durante l'epoca dei 32-bit, grazie ad una nutrita schiera di appassionati, collezionisti e produttori di videogiochi homebrew, tanto che la sua dismissione definitiva avvenne soltanto nel 2003, dopo oltre tredici anni dalla messa in vendita originale.");
        $(".Tr_desc_nin64").text("Il Nintendo 64 (abbreviato in N64) è una console da tavolo per videogiochi prodotta da Nintendo dal 1996 al 2002 e succeduta al Super Nintendo Entertainment System (SNES). La console utilizza le cartucce, nonostante appartenga a un'epoca in cui questi supporti erano ormai divenuti obsoleti per le console da tavolo e la concorrenza utilizzava il CD-ROM. Il nome si riferisce ai 64 bit del suo microprocessore, sebbene il bus dati sia ridotto in realtà a 32 bit. Si trattava di un sistema fortemente orientato alla grafica tridimensionale, grazie a un notevole coprocessore grafico. Il Nintendo 64 ebbe buon successo, con oltre 32 milioni di unità vendute, ma sono molte meno rispetto alla concorrente PlayStation e meno anche rispetto allo SNES.");
        $(".Tr_desc_gba").text("Il Game Boy Advance, abbreviato ufficialmente GBA, è una console portatile a 32 bit sviluppata, prodotta e commercializzata dalla Nintendo nel 2001. Succede al Game Boy Color. Competeva commercialmente con il WonderSwan Color, il GP32 e il N-Gage, occupando comunque la maggior parte del mercato. È stata la prima console portatile Nintendo a superare le caratteristiche tecniche dell'Atari Lynx, caratteristiche che rendono il Game Boy Advance simile allo SNES. Pur utilizzando cartucce differenti rispetto a quelle del Game Boy e Game Boy Color, il Game Boy Advance rimane compatibile con queste ultime grazie alla presenza di un coprocessore Z80, che garantisce la retrocompatibilità. Il Game Boy Advance con il suo processore ARM7TDMI a 16,78 MHz, nonostante gestisca alcune basi del 3D, non è dotato di reale supporto hardware per la renderizzazione della grafica poligonale 3D, ma con la discreta potenza del processore era perfettamente possibile la realizzazione in software di mondi 3D fatti di un numero limitato di poligoni, texture mappate, sorgenti di luce e ombre.");
        $(".Tr_desc_ninCube").text("Il Nintendo GameCube , anche noto come GameCube(abbreviato come NGC in Giappone o GCN in Europa e Nord America), è una console prodotta da Nintendo. È stata una console di sesta generazione, assieme a Dreamcast, PlayStation 2 e Xbox. Commercializzata tra il 2001 e il 2007, la quarta console prodotta dall'azienda giapponese è stata annunciata come successore del Nintendo 64 con il nome in codice 'Dolphin' (sebbene sia stata internamente indicata inizialmente come 'N2000' e 'Project Dolphin'). GameCube è stata la prima console Nintendo a utilizzare i dischi ottici come supporto di memorizzazione principale. I suoi dischi, in formato simil–mini DVD, lo rendevano un sistema non progettato per riprodurre DVD di dimensioni standard o CD audio, a differenza delle sue concorrenti contemporanee, portando il sistema a specializzarsi esclusivamente sui videogiochi. La console ebbe un supporto per il gioco in rete, ma in modo limitato e con pochi titoli, tramite una scheda di rete a connessione a banda larga o un adattatore per modem a 56 kbit/s e può connettersi alla console portatile Game Boy Advance, tramite cavo apposito, che consente ai giocatori di accedere a funzionalità di gioco esclusive utilizzando la portatile come secondo schermo e controller. L'accoglienza raccolta dal GameCube fu generalmente positiva. La console venne elogiata per il suo controller, una vasta libreria di software e videogiochi di alta qualità, ma è stata criticata per la sua apparenza estetica e la mancanza di alcune funzionalità.");
        $(".Tr_desc_ninDS").text("Il Nintendo DS è una console portatile ideata e fabbricata da Nintendo, presentata nel 2004. La console presenta un design a conchiglia, e possiede due schermi LCD al suo interno – uno dei quali è uno schermo tattile. Il DS offre anche un microfono incorporato e supporta la connettività wireless IEEE 802.11 (Wi-Fi), grazie al servizio di gaming online Nintendo Wi-Fi Connection. È stata la prima console Nintendo ad essere commercializzata prima in Nord America (21 novembre 2004) che in Giappone (2 dicembre 2004). Qualche mese più tardi è uscita nei negozi anche in Australia (24 febbraio 2005) e, per ultima, in Europa (11 marzo 2005). È attualmente la seconda console più venduta della storia dopo la PlayStation 2. Sul territorio europeo è stato commercializzato in 9 colori: bianco, nero, argento, blu, rosa, rosso, grigio, verde e azzurro. Dopo oltre sei anni, l'intera serie delle console Nintendo DS è stata affiancata e poi sostituita dal Nintendo 3DS, la nuova console portatile di Nintendo, che ha esordito in Europa il 25 marzo 2011. La console è stata d'altra parte già dismessa nel 2009 e i giochi sono rimasti utilizzabili per Nintendo DSi e Nintendo DSi XL fino al 20 maggio 2014 quando Nintendo ha annunciato che non sarebbero stati più disponibili, come il servizio Nintendo Wi-Fi Connection.");
        $(".Tr_desc_wii").text("Wii è una console per videogiochi, prodotta dall'azienda giapponese Nintendo, lanciata sul mercato nel 2006. Erede del Nintendo GameCube, i suoi 101,63 milioni di unità vendute l'hanno resa la console casalinga più popolare della settima generazione e la seconda di Nintendo, superata solo da Nintendo Switch. Wii è stato il principale concorrente di Xbox 360 di Microsoft e di PlayStation 3 di Sony. La console si distingue dalle altre della sua epoca, e dalle precedenti, per la possibilità di interagire col videogioco attraverso il movimento delle braccia, e per avere un sistema di puntamento allo schermo. Queste due caratteristiche non sono una novità assoluta nel mondo dei videogiochi, ma per la prima volta sono state integrate in una console senza ricorrere a periferiche aggiuntive. Il cardine dell'innovazione è il controller, chiamato Telecomando Wii, nella forma ricorda un telecomando ed è impugnabile con una sola mano, oltre ad avere una dotazione di tasti abbastanza classica, è dotato di un accelerometro per la rilevazione del movimento, e di un sensore IR posto sulla sua sommità, tale sensore abbinato alla Sensor Bar (presente nella confezione della console) consente il puntamento allo schermo. Nella confezione di Wii si trova inoltre il Nunchuk, una espansione del Telecomando Wii che si collega ad esso via cavo e si impugna con una sola mano, ha al suo interno un accelerometro, così da rilevare i movimenti del secondo braccio, ed aggiunge uno stick analogico e due tasti dorsali.");
        $(".Tr_desc_wiiu").text("Wii U è una console per videogiochi prodotta da Nintendo. Succede a Wii pur non sostituendolo in alcuni paesi ed è stata la prima console da tavolo dell'ottava generazione ad essere immessa sul mercato. I suoi principali concorrenti sono PlayStation 4 di Sony e Xbox One di Microsoft. Nintendo iniziò lo sviluppo del Wii U nel 2008, dopo aver riconosciuto alcuni limiti intrinseci del Wii, vista dal pubblico come console troppo 'casual' rispetto alle principali concorrenti sia da un punto di vista ludico che tecnico. Le critiche più comuni rivolte al sistema riguardavano ad esempio l'assenza del supporto per l'alta definizione e di una consistente modalità multigiocatore in rete. Attraverso Wii U, Nintendo intendeva quindi riportare i giocatori 'hardcore' sulla sua piattaforma e per far ciò decise che un nuovo hardware era necessario. Vennero discusse diverse idee relative alla strada da seguire per realizzare l'obiettivo e per questo il progetto ripartì da zero in più occasioni. Infine, dopo aver pensato anche di installare un piccolo schermo sul controller per indicare alcune informazioni al giocatore (idea simile al VMU del Sega Dreamcast), venne sviluppato un modello di gamepad con schermo di dimensioni generose che inizialmente si era pensato non economicamente realizzabile.");
        $(".Tr_desc_nin3DS").text("Nintendo 3DS è una console portatile per videogiochi prodotta da Nintendo e la prima ad appartenere all'ottava generazione di console videoludiche. La sua particolarità è lo schermo superiore che permette di visualizzare giochi, immagini e video in 3D, senza l'uso di occhiali speciali. È stato presentato ufficialmente all'E3 del 2010, il 15 giugno. Il 14 aprile 2010, durante un'intervista, il presidente di Nintendo of America, Reggie Fils-Aime, confermò che il 3DS sarebbe stata la nuova console portatile di Nintendo, introducendo una volta per tutte l'ottava generazione delle console per videogiochi. Durante il Nintendo Direct del 22 giugno 2012 Nintendo ha presentato Nintendo 3DS XL, una versione più grande dell'attuale console. Il 17 settembre 2020, a quasi dieci anni dal lancio del primo modello della console, Nintendo ne ha annunciato le dismissioni e l'interruzione della produzione di tutti i modelli introdotti sul mercato.");
        $(".Tr_desc_ninSwitch").text("Nintendo Switch, inizialmente conosciuta con il nome in codice di NX, è una console a 64 bit di natura ibrida sviluppata da Nintendo e distribuita in tutto il mondo a partire dal 3 marzo 2017. Nintendo Switch è stata ufficialmente rivelata il 20 ottobre 2016 ed è arrivata sul mercato in Giappone, Europa e America del Nord il 3 marzo 2017. Switch rappresenta il primo tentativo da parte di Nintendo di creare una console ibrida tra una casalinga e una portatile essendo dotata di un supporto basato su cartuccia elettronica, formato in precedenza abbandonato da Nintendo dopo il Nintendo 64 nel settore delle console fisse ma adottato in tutte le console portatili, alle quali le cartucce per Switch assomigliano. È la seconda console più di successo di Nintendo, superata solo dal Nintendo DS in termini di unità vendute, nonché la terza in assoluto, dietro alla PlayStation 2 e allo stesso DS. Compete commercialmente con le console di ottava generazione, PlayStation 4 della Sony e Xbox One della Microsoft, generazione nella quale viene comunemente inclusa dalla stampa specializzata.Tuttavia, Nintendo ha annunciato che, a causa del suo enorme successo, ha intenzione di continuare a supportare la console per ancora molti anni, attraversando così anche tutta la nona generazione. Ciò l'ha portata, nella seconda parte del suo ciclo produttivo, a dividere il mercato anche con PlayStation 5 e Xbox Series X e Series S, commercializzate a fine 2020.");

        /*Prezzo-Unità*/
        $(".tr_price_NES").text("Prezzo di lancio: $89,99");
        $(".tr_units_NES").text("Totale unità vendute: 61,91 milioni");
        $(".tr_price_gameBoy").text("Prezzo di lancio: $89,99");
        $(".tr_units_gameBoy").text("Totale unità vendute: 118 milioni");
        $(".tr_price_SNES").text("Prezzo di lancio: $199,99");
        $(".tr_units_SNES").text("Totale unità vendute: 49,1 milioni");
        $(".tr_price_nin64").text("Prezzo di lancio: $199,99");
        $(".tr_units_nin64").text("Totale unità vendute: 32,92 milioni");
        $(".tr_price_gba").text("Prezzo di lancio: $99,99");
        $(".tr_units_gba").text("Totale unità vendute: 81,5 milioni");
        $(".tr_price_ninCube").text("Prezzo di lancio: $199,99");
        $(".tr_units_ninCube").text("Totale unità vendute: 21,74 milioni");
        $(".tr_price_ninDS").text("Prezzo di lancio: $120,00");
        $(".tr_units_ninDS").text("Totale unità vendute: 153,99 milioni");
        $(".tr_price_wii").text("Prezzo di lancio: $249,99");
        $(".tr_units_wii").text("Totale unità vendute: 101,63 milioni");
        $(".tr_price_wiiu").text("Prezzo di lancio: $299,99");
        $(".tr_units_wiiu").text("Totale unità vendute: 13,56 milioni");
        $(".tr_price_nin3DS").text("Prezzo di lancio: $249,99");
        $(".tr_units_nin3DS").text("Totale unità vendute: 76 milioni");
        $(".tr_price_ninSwitch").text("Prezzo di lancio: $299,99");
        $(".tr_units_ninSwitch").text("Totale unità vendute: 122,55 milioni");
    });
});

/*=================================================================*/
/*===SEGA===*/

//English
$(function () {
    $(".en").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescSega").text("Sega is a video game manufacturer, it published video games and also produced multiple consoles. Its headquarters are located in Tokyo, Japan. Sega was primarily formed on the creation of slot machines and arcade games in 1964 and produced many video games for arcades. But after a slump in demand for arcade games in 1980, Sega began producing video games and consoles as well with the first Sega-branded console, the Japa-only SG-1000, becoming one of the first companies to compete against Nintendo in the console market. The Sega branded consoles, later on, proved a failure and the final blow was given in 2001 with the Dreamcast console which brought the decision, by the leaders of Sega, not to produce more consoles but to choose to become video game manufacturers.");
        $(".Tr_desc_sg1000").text("Japan-only SG-1000 released in 1983 was the first console produced that allowed you to play comfortably at home. There was a computer variant the SC-3000 and a year later an improvement of the SG-1000 came out, the SG-1000 II, finally in 1985 they upgraded the SG-1000 II model, calling it the Sega Mark III.");
        $(".Tr_desc_masterSystem").text("Master system also known as Sega Mark III, is the third generation of the SG-1000, which changed its name to Master system when it was also released in America, Korea and Brazil. The Master System Console was enhanced and a second edition was released, the Master System II which was also marketed in Europe. The master system was the generation of consoles that competed with Nintendo. It turned out though with the master system I had a smaller game library with a few games with very high ratings. It is estimated that between 10 and 13 million copies of the Sega master system have been sold worldwide.");
        $(".Tr_desc_genesis").text("The third console produced and sold by Sega, it is part of the new 16-bit consoles. It had more than 900 games and it was possible to add extensions (even produced by third parties), extensions that also allowed you to play the old Master System games on the new Sega Mega drive console. On the console market, in those times, there were also several other consoles and the PC engine, finally, with the release of the Super Nintendo, a real war called 'Console war' was born. Ultimately, sega was able to see 30.75 million copies of the Mega drive.");
        $(".Tr_desc_gameGear").text("The end of 2020 also brought with it the long-awaited generational leap and the new Xbox Series X and S are representing a real rebirth for the brand, after the gloomy generation of One. The first year of the consoles has certainly made it clear that there is a lot of interest from the market for Microsoft's gaming proposal, and this is coming thanks to a clear change of course on the communication front. Microsoft has reinvented gaming not with the new consoles but with its Game Pass service, the Netflix of video games: with 14 euros a month for its Ultimate version, a library of over 100 games is included.");
        $(".Tr_desc_saturn").text("On the coveted console Sega produced a new product in the fifth console generation, the sega Saturn successor of the sega genesis. The Sega Saturn went on the market with a new CPU and an additional graphics engine to be able to give a better resolution on screen, this time in competition, was the PlayStation. It was a big hit in Japan, but not in America due to the advent of the PS.");
        $(".Tr_desc_dreamcast").text("The Dreamcast is a 32-bit video game console manufactured by SEGA between 1998 and 2001, released in Japan on November 27, 1998, September 9, 1999 in North America and October 14, 1999 in Europe. Dreamcast was the first sixth generation console, followed later by PlayStation 2, GameCube and Xbox. It was also SEGA's last home console, marking the end of its 18-year presence in the tabletop gaming system market. In contrast to the Sega Saturn's expensive and criticized hardware, the Dreamcast was designed with more homologated components to reduce costs, including a Hitachi SuperH 4 CPU and NEC PowerVR GPU. The release in Japan led to a moderate reception, while in the United States the console enjoyed success supported by a large marketing campaign, but interest would then steadily decline due to the expectation generated by Sony around the PlayStation 2. Sales they did not meet SEGA's expectations, despite several price cuts, and the company continued to suffer significant financial losses. After a change in leadership, Sega discontinued the Dreamcast on March 31, 2001, retiring from console development and restructured as a third-party developer and publisher. Approximately 9.13 million Dreamcast units were sold worldwide.");

        /*Prezzo-Unità*/
        $(".tr_price_sg1000").text("Introductory price: ¥15,000 (Only sold in Japan)");
        $(".tr_units_sg1000").text("Total units sold: 1.4 million");
        $(".tr_price_masterSystem").text("Introductory price: $200");
        $(".tr_units_masterSystem").text("Total units sold: 13 million");
        $(".tr_price_genesis").text("Introductory price: $170");
        $(".tr_units_genesis").text("Total units sold: 31 million");
        $(".tr_price_gameGear").text("Introductory Price: $149.99");
        $(".tr_units_gameGear").text("Total units Sold: 10.62 million");
        $(".tr_price_saturn").text("Introductory price: $399");
        $(".tr_units_saturn").text("Total Units Sold: 9.5 million");
        $(".tr_price_dreamcast").text("Introductory price: $199");
        $(".tr_units_dreamcast").text("Total Units Sold: 9.13 million");
    });
});

//Italian
$(function () {
    $(".it").click(function () {

        /*Descrizioni*/
        $(".Tr_storyDescSega").text("La Sega è una casa produttrice di video giochi, pubblicava videogiochi ed ha prodotto pure molteplici console. La sua sede è situata in Giappone a Tokyo. La Sega è stata principalmente formata sulla creazione di slot machine e arcade game nel 1964 e produsse molti videogiochi per le arcade. Ma dopo un crollo della domanda sugli arcade games nel 1980 la Sega iniziò a produrre pure video giochi e console con la prima console marcata Sega la Japa-only SG-1000, diventato una delle prime industrie a poter competere contro Nintendo nel mercato delle console. Le console marcate Sega, più in là con il tempo, si rilevarono un fallimento e la botta finale venne data nel 2001 con la console Dreamcast che porto la decisione, da parte degli apici della Sega, di non produrre più console ma di scegliere di diventare produttori di video giochi.");
        $(".Tr_desc_sg1000").text("Japan-only SG-1000 rilasciata nel 1983 fu la prima console prodotta che permettesse di giocare comodamente a casa. Ci fu una variante per computer la SC-3000 e un anno dopo uscì un miglioramento della SG-1000, la SG-1000 II, infine nel 1985 potenziarono il modello SG-1000 II, chiamandola Sega Mark III.");
        $(".Tr_desc_masterSystem").text("Master system anche conosciua come Sega Mark III, è la terza generazione della SG-1000, che cambio nome con Master system quando venne Poi pubblicata anche in America, Korea e Brasile. La Console Master system venne potenziata e uscì una seconda edizion, la Master System II che venne commercializzata anche in Europa. Il sistema master system è stata la generazione di console che entro un competizione con Nintendo. Si è visto però con la master system avevo una libreria di giochi più ristretta con pochi giochi con una valutazione molto alta. Si stima che della Sega master system si siano vendute tra le 10 e le 13 milioni di copie in tutto il mondo.");
        $(".Tr_desc_genesis").text("La terza console prodotta e venduta dalla Sega, fa parte delle nuove console a 16 bit. Disponeva di più di 900 giochi e era possibile aggiungerli delle estensioni (prodotte addirittura da terze parti), estensioni che permettvano di giocare anche i vecchi giochi del Master System sulla nuova console Sega Mega drive. Sul mercato console, in quei tempi, vi erano anche diverse altre cosnole e il PC engine, infine, con il rilascio del Super Nintendo, nacque una vera e propria guerra appellata come 'Console war'. In definitiva, sega riuscì a vedere 30.75 millioni di copie del Mega drive.");
        $(".Tr_desc_gameGear").text("E' stata la prima console portatile della Sega a competizione con il Nintendo game boy, condivide gran parte dell'hardware del master system e grazie ad un adattatore si poteva giocare ai giochi del master System. Il problema principale del game Gear era la sua unica libreria che però scarseggiava di giochi originali, il poco supporto da parte della sega, riuscì a vendere solo 10.6 milioni, un anno dopo è stata bloccata la produzione del Game Gear.");
        $(".Tr_desc_saturn").text("Sull'ambito console la Sega produsse nella quinta generazione di console un nuovo prodotto, il sega Saturn successore del sega genesis. La sega Saturn entro in commercio con una nuova CPU e un motore grafico aggiuntivo per poter dare una migliore risoluzione su schermo, questa volta in competizione, era la PlayStation. Fu un gran successo in Giappone, ma non in America accausa dell'avvento della PS.");
        $(".Tr_desc_dreamcast").text("Il Dreamcast è una console per videogiochi a 32-bit prodotta da SEGA tra il 1998 e il 2001, commercializzata in Giappone a partire dal 27 novembre 1998, il 9 settembre 1999 in America del Nord e il 14 ottobre 1999 in Europa. Dreamcast è stata la prima console di sesta generazione, seguita successivamente da PlayStation 2, GameCube e Xbox. È stata, inoltre, l'ultima console domestica di SEGA, segnando la fine dei suoi 18 anni di presenza nel mercato dei sistemi da gioco da tavolo. Contrariamente al costoso e criticato hardware del Sega Saturn, il Dreamcast venne progettato con componenti più omologati per ridurre i costi, tra cui una CPU Hitachi SuperH 4 e una GPU NEC PowerVR. La pubblicazione in Giappone portò a una discreta accoglienza, mentre negli Stati Uniti la console godette di successo supportato da una grande campagna di marketing, ma l'interesse sarebbe poi costantemente diminuito a causa dell'aspettativa generata da Sony intorno a PlayStation 2. Le vendite non soddisfecero le aspettative di SEGA, nonostante diversi tagli dei prezzi, e la società continuò a subire significative perdite finanziarie. Dopo un cambio di leadership, SEGA interruppe la produzione del Dreamcast il 31 marzo 2001, ritirandosi dallo sviluppo di console e ristrutturandosi come sviluppatore e publisher di terze parti. Circa 9,13 milioni di unità Dreamcast vennero vendute in tutto il mondo.");
        /*Prezzo-Unità*/
        $(".tr_price_sg1000").text("Prezzo di lancio: ¥15.000 (Venduto solo in Giappone)");
        $(".tr_units_sg1000").text("Totale unità vendute: 1,4 milioni");
        $(".tr_price_masterSystem").text("Prezzo di lancio: $200");
        $(".tr_units_masterSystem").text("Totale unità vendute: 13 milioni");
        $(".tr_price_genesis").text("Prezzo di lancio: $170");
        $(".tr_units_genesis").text("Totale unità vendute: 31 milioni");
        $(".tr_price_gameGear").text("Prezzo di lancio: $149,99");
        $(".tr_units_gameGear").text("Totale unità vendute: 10,62 milioni");
        $(".tr_price_saturn").text("Prezzo di lancio: $399");
        $(".tr_units_saturn").text("Totale unità vendute: 9,5 milioni");
        $(".tr_price_dreamcast").text("Prezzo di lancio: $199");
        $(".tr_units_dreamcast").text("Totale unità vendute: 9,13 milioni");
    });
});